### ISSUE TITLE
Cached results after clear key

### ISSUE THREAD

**Issue by po5i** [erictrinh/jquery-memoized-ajax#5]
It seems after clearing the cache key under session storage o local storage, ajax calls still return cached response. I can see that because no further request are made in the browser (but a new cache is creating under the same key as expected).

If the page is refreshed and the cache key is cleared, normal requests are made normally.

Is there anything I should do to really clear the cache in runtime?

**Comment by erictrinh** [comment]
It's probably because memoizedAjax will cache results fetched from local storage into memory for performance reasons. This does seem like buggy behavior though. If `localStorage: true` or `sessionStorage: true` are passed, memoizedAjax should only read from those stores, not memory. I'd be willing to accept a PR that fixes this, or I can take a look at it later in the week.

**Comment by po5i** [comment]
`sessionStorage: true` is passed in the options array in my case.

**Comment by erictrinh** [comment]
@po5i can you test the latest `jquery.memoized.ajax.js` in master to see if it fixes your use case? I refactored/rewrote a bunch of the tests as well, so a little bit wary of whether it works 100% correctly. I'll do some more extensive testing this weekend before bumping version.

**Comment by po5i** [comment]
@erictrinh Now it works perfectly, when I delete the key a new request is made. Thanks.

Could you please update the bower package anytime you can?

**Comment by erictrinh** [comment]
Well that took longer than was reasonable, but I just pushed 0.5.0 to bower and npm. Happy new year!
